### ISSUE TITLE
회원가입 ui 제작

### ISSUE THREAD

**Issue by yura0302** [Techeer-3rd-COKKIRI/frontend#2]

**Comment by JeongHunHui** [comment]
기능구현 해주시기 전에 이슈템플릿 추가해주시고, 이슈템플릿에 맞춰서 이슈 생성해주시면 좋을것같아요!
노션에 있는 github commit convention 참고하시면 됩니다!

**Comment by Leeseunghwan7305** [comment]
넵 알겠습니다 !

**Comment by Leeseunghwan7305** [comment]
> 기능구현 해주시기 전에 이슈템플릿 추가해주시고, 이슈템플릿에 맞춰서 이슈 생성해주시면 좋을것같아요! 노션에 있는 github commit convention 참고하시면 됩니다!

넵 알겠습니다 !
